name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run typecheck

    - name: Run build
      run: npm run build

    - name: Check code formatting and linting
      run: npm run check

    - name: Fix code formatting and linting
      run: npm run check:fix

    # For pushes to main or PRs from same repo, commit formatting changes
    - name: Commit changes
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: format code with biome"
        branch: ${{ github.event_name == 'push' && 'main' || github.head_ref }}

    # For PRs from forks, fail the check if there are formatting changes required
    - name: Check for uncommitted changes
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "::error::Code formatting issues found. Please run 'npm run check:fix' locally and commit the changes."
          git diff
          exit 1
        fi
