name: Integration test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['18', '20', '22', '24']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Reinstall Biome (fix platform-specific binary)
      run: npm install @biomejs/biome --force

    - name: Run build and type checks
      run: |
        npm run typecheck
        npm run check
        npm run build

    - name: Create models directory (Unix)
      if: runner.os != 'Windows'
      run: mkdir -p .models

    - name: Create models directory (Windows)
      if: runner.os == 'Windows'
      run: mkdir .models

    - name: Run integration test (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: npm test
      env:
        NODE_ENV: test
